# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs a single command using the runners shell
      - name: make new readme file
        run: touch README3.md
        
      - name: Deploy Readme-3
        # You may pin to the exact commit or the version.
        # uses: Burnett01/rsync-deployments@45d84ad5f6c174f3e0ffc50e9060a9666d09c16e
        uses: Burnett01/rsync-deployments@6.0.0
        with:
          # The switches
          switches: -avzr --delete --exclude=".git" --exclude=".github"
          # The local path of dir/file will added
          path: /README3.md
          # The remote path
          remote_path: /home/${{ secrets.USER }}/public_html
          # The remote host
          remote_host: ${{ secrets.HOST }}
          # The remote port
          remote_port: ${{ secrets.PORT }}
          # The remote user
          remote_user: ${{ secrets.USER }}
          # The remote key
          remote_key: ${{ secrets.DEPLOY_KEY }}
          remote_key_pass: ${{ secrets.PASSPHRASE }}

          
      - name: Deploy Readme-all
        # You may pin to the exact commit or the version.
        # uses: Burnett01/rsync-deployments@45d84ad5f6c174f3e0ffc50e9060a9666d09c16e
        uses: Burnett01/rsync-deployments@6.0.0
        with:
          # The switches
          switches: -avzr --delete --exclude=".git" --exclude=".github" --exclude="README3.md"
          # The local path of dir/file will added
          path: /
          # The remote path
          remote_path: /home/${{ secrets.USER }}/project
           # The remote host
          remote_host: ${{ secrets.HOST }}
          # The remote port
          remote_port: ${{ secrets.PORT }}
          # The remote user
          remote_user: ${{ secrets.USER }}
          # The remote key
          remote_key: ${{ secrets.DEPLOY_KEY }}
          remote_key_pass: ${{ secrets.PASSPHRASE }}
          
                
      
            
